### ISSUE TITLE
How important is it to add a CI utility to a small college project?

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/aua#1]
Talking about B.Tech., we are supposed to work on a lot of projects related to the curriculum. And many of them become ambitious and we barely manage to complete what we proposed in time. In such situations, should we care about setting up CIs and writing tests?

**Comment by aviaryan** [comment]
IMO, you should write tests only when you are quite confident about the technologies you are using in the project. In case of a B.Tech project, it can be assumed that you are going to work in a team and so you will have members with varied proficiency. In that case, if you pump up the level by adding CI and other spices, some members will feel left out of the project and will stop caring about it. 
So it would be better if you keep the project simple as possible. If you are going to add CI and stuff anyway, don't make it compulsory for others to do that too. Let them follow the straight-forward way to do things. If they are screwing up, try to be gentle when pointing out their mistakes. If needed, correct their mistakes yourself to show them how it's done.
