### ISSUE TITLE
Resources for Jade

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#11]
Jade is a templating engine, I am using it as a templating engine for learning express, but i wasn't able to fully use it, upto it's strength. Any help is appreciated, Also want to know is there are better templating engines from this. What are their pro's and con's? Experience of working with Express?

**Comment by aviaryan** [comment]
@ansarimofid

**Comment by yashLadha** [comment]
Is Jade deprecated, or should i move to pug?

**Comment by aviaryan** [comment]
Yes, you should move to pug.

**Comment by ansarimofid** [comment]
Jade is renamed as pug. Everything remains same. And for learning it's documentation is enough to get started

**Comment by yashLadha** [comment]
thanks @aviaryan @ansarimofid , i am working on it. :+1:
