### ISSUE TITLE
What are promises in mongoose?

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#12]
Getting deprecation warning while saving a model instance.

**Comment by aviaryan** [comment]
Promises are an ES5 concept. You can find a lot of documentation online. Let me know if you have any questions.

**Comment by yashLadha** [comment]
It is giving me warning when a model Instance is saved. How it is related to that? I have seen that on `execute()` command it sends Promise. But how it is needed while saving, i have no clue?

**Comment by aviaryan** [comment]
Sample code? How are you running it? Node version?

**Comment by yashLadha** [comment]
Now the problem is solving after using global.promise. @aviaryan can you explain it why?

**Comment by singhpratyush** [comment]
@yashLadha: Please provide relevant information to @aviaryan so that he can provide you a clear solution. Thanks.

**Comment by yashLadha** [comment]
I understood the concept later @singhpratyush . Thanks for the help @aviaryan . Closing this issue.
