### ISSUE TITLE
Resources for Vector animation Android

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#16]
I want to learn vector animation in android but unable to find some good resources for it.

**Comment by aviaryan** [comment]
@bxute

**Comment by singhpratyush** [comment]
@yashLadha: Have you tried [`android.graphics.drawable.AnimatedVectorDrawable`](https://developer.android.com/reference/android/graphics/drawable/AnimatedVectorDrawable.html)?

Though I have never used it, I have seen devs discussing it at many places. Hope it helps.

**Comment by yashLadha** [comment]
Thanks sir @singhpratyush  :+1: :smile:
