### ISSUE TITLE
Visualize a 4D dataset in python

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#17]
How can i visualize 4d (4 features dataset) efficiently in python?

**Comment by Prakash2403** [comment]
For me, `numpy.ndarray` did the job. I think that it's the best option available for now.

**Comment by yashLadha** [comment]
What about visualizing data on a plot. Is it possible to present more than 3 Dimension in python

**Comment by Prakash2403** [comment]
In short, we can't visualize 4D plots, at least not in physics(ping me if you are interested to know why we can't *see* through the fourth dimension in physics). Mathematically, you can try to visualize as follows.

 Taken from quora

> Imagine, if you will, how your visual system works for 3D. You have 2 3D eyes with 2D retinas, and a brain to reconstruct the 3D from them.
Now, do the obvious transformation. You have 2 4D eyes with 3D retinas with a brain to reconstruct the 4D scene. Note that your brain can still remain 3D. It just needs to be wired to these 4D retinas, so the optical nerves will be a bit thicker, etc., but those are "unimportant" details.
Think of how your brain would reconstruct that scene. Try to "see" through those 4D eyes yourself. You have to think very carefully about this, but if you try it enough, you should be able to get a glimpse of what 4d vision would be like. That is, if your brain does not explode first.
Doing this led me immediately to the insight that -- ignoring the impossible physics for a moment -- flipping your 3D body into the 4th dimension would lead to non-containment of your organs. They would -- along with your blood and all -- just slip out and drift everywhere.

Source link [How to imagine 4D](https://www.quora.com/How-can-we-imagine-the-4th-dimension)


EDIT

A trick to visualize 4D data in 3D [SO](https://stackoverflow.com/questions/31806254/plotting-4d-data).

**Comment by nileshchat** [comment]
Most people use `color gradient` or `shapes` for datapoints to represent data in more than 3 dimensions. 
This [link](https://plot.ly/python/line-and-scatter/#simple-scatter-plot) can be of help.

**Comment by yashLadha** [comment]
Thanks for sharing your views @Nilesh4145 @Prakash2403. I appreciate your views
