### ISSUE TITLE
python3 supported library for Weather-Forecast

### ISSUE THREAD

**Issue by neelanshsahai** [iiitv/aua#18]
Can anyone suggest a stable library for weather forecast that doesn't require any oauth key.
I found a library named `pyowm` but it was not supported for python 3.5

**Comment by aashutoshrathi** [comment]
Try this: https://pypi.python.org/pypi/yweather/

**Comment by Monal5031** [comment]
@neelanshsahai Sir but the README of `pyowm` says that it is supported for python 3.2+.
