### ISSUE TITLE
Please give me the details of the new PDPU hostel campus.

### ISSUE THREAD

**Issue by aviaryan** [iiitv/aua#2]
Images would be 👌🏻

The things I am most concerned about are ... drinking water, Internet, room capacity, canteen, sports facility, transport to college etc.

**Comment by aashutoshrathi** [comment]
![img-20170528-wa0067](https://user-images.githubusercontent.com/21199234/26974666-0fc04110-4d3a-11e7-9d3a-4880b571c0b8.jpg)
![img-20170528-wa0068](https://user-images.githubusercontent.com/21199234/26974667-0fc6b75c-4d3a-11e7-9971-c918f348a2a4.jpg)
![img-20170528-wa0070](https://user-images.githubusercontent.com/21199234/26974668-0fcea296-4d3a-11e7-9593-0e05adb077b6.jpg)
![img-20170528-wa0071](https://user-images.githubusercontent.com/21199234/26974669-0ff2a61e-4d3a-11e7-9bca-4fdb7cbf185e.jpg)
![img-20170528-wa0072](https://user-images.githubusercontent.com/21199234/26974670-0ff90d4c-4d3a-11e7-8fa6-2b6182a61ae4.jpg)
![img-20170528-wa0073](https://user-images.githubusercontent.com/21199234/26974671-1003abb2-4d3a-11e7-884d-ec34c7d34926.jpg)
![img-20170528-wa0074](https://user-images.githubusercontent.com/21199234/26974672-10077f08-4d3a-11e7-93be-c266f5ee7295.jpg)
![img-20170528-wa0075](https://user-images.githubusercontent.com/21199234/26974675-102edf76-4d3a-11e7-8e50-2c5a2f65251d.jpg)
No information about Internet and transport

**Comment by harishkrupo** [comment]
Looks Great! :+1:

**Comment by aviaryan** [comment]
Thanks @aashutoshrathi . I have heard we have access to PDPU internet there.
