### ISSUE TITLE
Source references for js

### ISSUE THREAD

**Issue by Monal5031** [iiitv/aua#3]
Please share references or websites for learning Node or React js.

**Comment by aviaryan** [comment]
For ReactJS, I recommend going through [Build With React](http://buildwithreact.com/tutorial). They have an interactive tutorial that teaches you main concepts of React quickly. 
After that, you can go through [React official docs](https://facebook.github.io/react/docs/installation.html).

**Comment by singhpratyush** [comment]
After that, you may set up an advanced workflow with `babel` and `webpack` following [this tutorial](https://scotch.io/tutorials/setup-a-react-environment-using-webpack-and-babel).

**Comment by Monal5031** [comment]
Thanks for the help 😄

**Comment by aviaryan** [comment]
Do you have more questions @Monal5031? If no, please close this issue.
