### ISSUE TITLE
Sources for learning advance Javascript

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#4]
From where can i learn the advance concepts of Javascript. So that i can use it to make some cool webapps.

**Comment by ansarimofid** [comment]
https://scotch.io/
Here you will find cool webapps built with javascript frameworks

**Comment by ansarimofid** [comment]
For advance concept of VanillaJS, I recommend reading [You Don't Know Js Series](https://github.com/getify/You-Dont-Know-JS)

**Comment by yashLadha** [comment]
How these different js versions like vanillaJS, node.js are different from each other?

**Comment by yashLadha** [comment]
Is [http://scotch.io/](http://scotch.io/) is a free website or not? I am looking for free and open alternatives.

**Comment by ansarimofid** [comment]
Pure javaScript without any framework is called vanillaJS while nodejs is a tool which enables javaScript to run outside of browser. Due to nodejs we are abe to build software from end to end using javaScript..

**Comment by ansarimofid** [comment]
http://scotch.io/  is totally free

**Comment by yashLadha** [comment]
Sir, when i clicked on course, it is saying me to singup and pay some money.

**Comment by ansarimofid** [comment]
Don't go for the course, go for tutorials. Everything used to be free there, but now I think they have added some paid courses.

**Comment by yashLadha** [comment]
Thanks for suggestion :+1:
