### ISSUE TITLE
Regex Tutorial

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#5]
I recently find that regex are powerful tool for filtering particular set of data from a chunk. I was unable to understand those regex, as particularly i want to scrap links from page requests. Is there any good tutorial available for REGEX and learning them with python.

**Comment by nileshchat** [comment]
Did you try hackerrank for the tutorial, they have a decent collection of tutorials

**Comment by yashLadha** [comment]
Thanks for suggestion @Nilesh4145
