### ISSUE TITLE
Brief Introduction to Haskell (Sources)

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/aua#6]
For learning Haskell, I first preferred the official site and http://learnyouahaskell.com but that's alot , is there some source where I can get brief description covering all basics.

**Comment by aviaryan** [comment]
You can try https://learnxinyminutes.com/docs/haskell/ which uses code to teach Haskell. 
For PDFs, you can check https://github.com/aviaryan/learnxinyminutes-pdf 😜

**Comment by aashutoshrathi** [comment]
Thanks, I already had that PDF BTW 😄
