### ISSUE TITLE
Passing Django model objects to Javascript

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#7]
Is passing django model objects to javascript function's possible? Is there a way to call functions of those respective models in the javascript code? Need help!!!

**Comment by singhpratyush** [comment]
```jinja
<script>
    let user = {{ user.name }};
</script>
```

**Comment by yashLadha** [comment]
@singhpratyush Sir can i also call a function with no arguments. I have tried to use this but it showed me Syntax Error.

**Comment by singhpratyush** [comment]
```jinja
<div user-token={{ user.generate_token }}>
```
Where `user` is an instance of
```python
class ...(...):
    ...
    def generate_token(self):
        ...
        return token
    ...
```

**Comment by yashLadha** [comment]
Sir i am saying that is these functions are callable from javascript code too? Because i am having problem in sending objects to functions (Javascript).

**Comment by singhpratyush** [comment]
Jinja templates are generated before returning a response to the user. You can't use these functions (or anything related to `jinja`) at the client side.

But you can pack these variables in advance hand before sending the response, as shown in the comment.

**Comment by yashLadha** [comment]
That means i can't call call model functions from javascript code.

**Comment by yashLadha** [comment]
Thanks @singhpratyush  Sir. :+1:
