### ISSUE TITLE
What is signing the commits??

### ISSUE THREAD

**Issue by yashLadha** [iiitv/aua#9]
I recently reviewed a PR and the commit message have labels attached to them as verified. What is the importance of signing commits and how it is used in an organisation?

**Comment by harishkrupo** [comment]
Signing is one way to denote the authorship of a commit (by default the author of the commit is the person who commits). Many times multiple people contribute to the commit by suggesting different methods or working together (pair programming). This is when signed off is useful. Multiple people can add their signed off to show their contribution to the commit. In organizations, the CI tool sometimes tracks authorship using signed off.
Tip: you can add the signed off automatically by  using `git commit -s`

**Comment by yashLadha** [comment]
Thanks @harishkrupo for your response. :+1:
